server:
  port: 8080
  context-path: /eatlab-dms
  connection-timeout: 150000
  use-forward-headers: true

spring:
  application:
    name: eatlab-dms
  data:
    mongodb:
      host: localhost
      port: 27017
      database: eatlab

eatlab:
  dms:
    server:
      directory: /var/eatlab/data
      jsonDataFileName: order.json
      sambaShare: smb://192.168.0.199/eatlabdata/
      allowedTokens: 1234,21345
      fixBrokenJson: true

logging:
  level:
    org:
      springframework:
        #data: DEBUG
        #web: DEBUG

---
spring.profiles: dev

eatlab:
  dms:
    server:
      directory: /Users/ton/test
      sambaShare: smb://localhost/test/

---
spring.profiles: dev-atom

eatlab:
  dms:
    server:
      directory: F:\temp\eatlab_test\server
      sambaShare: F:\temp\eatlab_test\server
