// <auto-generated />
using System;
using EDI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EDI.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220204121513_FlattenOrderTable")]
    partial class FlattenOrderTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeAllowanceOrChargeCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeAllowanceOrChargeCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeDateTimePeriodFormatCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeDateTimePeriodFormatCode");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeDateTimePeriodFunctionCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeDateTimePeriodFunctionCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeDescriptionFormatCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeDescriptionFormatCode");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeDutyTaxFeeCategoryCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeDutyTaxFeeCategoryCode");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeDutyTaxFeeFunctionCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeDutyTaxFeeFunctionCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeDutyTaxFeeTypeNameCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeDutyTaxFeeTypeNameCode");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeItemTypeIdentificationCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeItemTypeIdentificationCode");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeLocationFunctionCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeLocationFunctionCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeMonetaryAmountTypeCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeMonetaryAmountTypeCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodePaymentTermsDescriptionIdentifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodePaymentTermsDescriptionIdentifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodePaymentTermsTypeCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodePaymentTermsTypeCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodePercentageTypeCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodePercentageTypeCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodePriceCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodePriceCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeQuantityTypeCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeQuantityTypeCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeReferenceCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeReferenceCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeSpecialServicedescriptionCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeSpecialServicedescriptionCode");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeTermsOfDeliveryOrTransportFunctionCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeTermsOfDeliveryOrTransportFunctionCode");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeTextSubjectCodeQualifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeTextSubjectCodeQualifier");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeTimeReferenceCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeTimeReferenceCode");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeTimeRelationCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeTimeRelationCode");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Codes.CodeTypePeriodCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeTypePeriodCode");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EDI_Contact");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.DeliveryOrTransportTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("EDI_DeliveryOrTransportTerm");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllowanceChargeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowanceDutyTaxFeeCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowanceDutyTaxFeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowanceDutyTaxFeeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AllowanceDutyTaxFeeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmountDutyTaxFeeCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmountDutyTaxFeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmountDutyTaxFeeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AmountDutyTaxFeeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodeListQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllingAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfPerparation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNameCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DutyTaxFeeCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DutyTaxFeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DutyTaxFeeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DutyTaxFeeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FreeTextCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InterchangeControlCount")
                        .HasColumnType("int");

                    b.Property<string>("InterchangeControlReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceMonetaryAmount")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceMonetaryCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceMonetaryTypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTestMessage")
                        .HasColumnType("bit");

                    b.Property<string>("MessageFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MonetaryAmount")
                        .HasColumnType("int");

                    b.Property<string>("MonetaryCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonetaryTypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfSegment")
                        .HasColumnType("int");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PercentageQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialServicesCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SumTaxMonetaryAmount")
                        .HasColumnType("int");

                    b.Property<string>("SumTaxMonetaryCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SumTaxMonetaryTypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SumTaxableMonetaryAmount")
                        .HasColumnType("int");

                    b.Property<string>("SumTaxableMonetaryCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SumTaxableMonetaryTypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyntaxIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyntaxVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaxableMonetaryAmount")
                        .HasColumnType("int");

                    b.Property<string>("TaxableMonetaryCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxableMonetaryTypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextLiteralFreeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextSubjectqualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalMonetaryAmount")
                        .HasColumnType("int");

                    b.Property<string>("TotalMonetaryCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalMonetaryTypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeReleaseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnhMessageReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnzInterchangeControlReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceeId");

                    b.ToTable("EDI_Invoice");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Buyer_ContactCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Buyer_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Buyer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Buyer_PartyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Buyer_PartyQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Buyer_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Buyer_ResponsibleAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeListQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllingAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfPerparation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Delivery1_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery1_FunctionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery1_PlaceLocationIdentification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery1_PlaceLocationQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery2_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery2_FunctionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery2_PlaceLocationIdentification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery2_PlaceLocationQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_PartyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_PartyName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_PartyName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_PartyQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_PlaceLocationIdentification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_PlaceLocationQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_ResponsibleAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNameCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreeTextCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InterchangeControlCount")
                        .HasColumnType("int");

                    b.Property<string>("InterchangeControlReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTestMessage")
                        .HasColumnType("bit");

                    b.Property<string>("MessageFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfSegment")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentTerm1_NumberOfPeriod")
                        .HasColumnType("int");

                    b.Property<decimal?>("PaymentTerm1_Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentTerm1_PercentageQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerm1_TimeReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerm1_TimeRelationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerm1_TypeOfPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerm1_TypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentTerm2_NumberOfPeriod")
                        .HasColumnType("int");

                    b.Property<decimal?>("PaymentTerm2_Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentTerm2_PercentageQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerm2_TimeReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerm2_TimeRelationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerm2_TypeOfPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerm2_TypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Supplier_CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_PartyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_PartyName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_PartyQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_ResponsibleAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyntaxIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyntaxVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextLiteralFreeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextSubjectqualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeReleaseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnhMessageReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnzInterchangeControlReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EDI_Order");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiOrderChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeListQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllingAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfPerparation")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNameCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreeTextCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InterchangeControlCount")
                        .HasColumnType("int");

                    b.Property<string>("InterchangeControlReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTestMessage")
                        .HasColumnType("bit");

                    b.Property<string>("MessageFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfSegment")
                        .HasColumnType("int");

                    b.Property<string>("RecipientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SyntaxIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyntaxVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextLiteralFreeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextSubjectqualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeReleaseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnhMessageReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnzInterchangeControlReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EDI_OrderChange");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiOrderConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeListQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllingAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfPerparation")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNameCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreeTextCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InterchangeControlCount")
                        .HasColumnType("int");

                    b.Property<string>("InterchangeControlReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTestMessage")
                        .HasColumnType("bit");

                    b.Property<string>("MessageFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfSegment")
                        .HasColumnType("int");

                    b.Property<string>("RecipientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SyntaxIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyntaxVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextLiteralFreeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextSubjectqualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeReleaseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnhMessageReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnzInterchangeControlReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EDI_OrderConfirmation");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiScheduleAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeListQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllingAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CurrentDeliveryReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentDeliveryReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentDeliveryReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfPerparation")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNameCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreeTextCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InterchangeControlCount")
                        .HasColumnType("int");

                    b.Property<string>("InterchangeControlReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTestMessage")
                        .HasColumnType("bit");

                    b.Property<string>("MessageFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfSegment")
                        .HasColumnType("int");

                    b.Property<DateTime>("PreviousDeliveryReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousDeliveryReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousDeliveryReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SyntaxIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyntaxVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextLiteralFreeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextSubjectqualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeReleaseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnhMessageReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnzInterchangeControlReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("EDI_ScheduleAgreement");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.FinancialInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountHolderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionBranchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionIdentification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EDI_FinancialInstitution");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.LineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalItemNumberType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdditionalProductId")
                        .HasColumnType("int");

                    b.Property<int?>("BackorderedQuantityId")
                        .HasColumnType("int");

                    b.Property<string>("CodeListQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeListResponsibleAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryLineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EdiInvoiceId")
                        .HasColumnType("INT");

                    b.Property<int?>("EdiOrderChangeId")
                        .HasColumnType("INT");

                    b.Property<int?>("EdiOrderConfirmationId")
                        .HasColumnType("INT");

                    b.Property<int?>("EdiOrderId")
                        .HasColumnType("INT");

                    b.Property<int?>("EdiScheduleAgreementId")
                        .HasColumnType("INT");

                    b.Property<string>("FreeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceDutyTaxFeeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceDutyTaxFeeRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceTax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCharacteristicCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDescriptionIdentification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDescriptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNumberType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MonetaryAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MonetaryCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonetaryTypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceMeasureUnitQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseLineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuantityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDeliveryReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceivedDeliveryReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedDeliveryReferenceQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceivedQuantityId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleConditionId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduledQuantityId")
                        .HasColumnType("int");

                    b.Property<string>("TaxCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TaxMonetaryAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxMonetaryCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxMonetaryTypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextFunctionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextSubjectQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitPriceBasis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BackorderedQuantityId");

                    b.HasIndex("EdiInvoiceId");

                    b.HasIndex("EdiOrderChangeId");

                    b.HasIndex("EdiOrderConfirmationId");

                    b.HasIndex("EdiOrderId");

                    b.HasIndex("EdiScheduleAgreementId");

                    b.HasIndex("QuantityId");

                    b.HasIndex("ReceivedQuantityId");

                    b.HasIndex("ScheduleConditionId");

                    b.HasIndex("ScheduledQuantityId");

                    b.ToTable("EDI_LineItem");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.NameAndAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FinancialInstitutionId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAndAddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATRegistrationQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("FinancialInstitutionId");

                    b.HasIndex("LocationId");

                    b.ToTable("EDI_NameAndAddress");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.PaymentTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfPeriod")
                        .HasColumnType("int");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PercentageQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsOfPaymentIdentification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsOfpayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeRelationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EDI_PaymentTerm");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.PlaceLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceLocationIdentification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceLocationQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EDI_PlaceLocation");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.Quantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QTYMeasureUnitQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuantityQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EDI_Quantity");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Request")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestLog");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.ScheduleCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryPlanStatusIndicatorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EarliestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LatestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuantityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuantityId");

                    b.ToTable("EDI_ScheduleCondition");
                });

            modelBuilder.Entity("Portal.Common.Entity.Entities.Audit.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.DeliveryOrTransportTerm", b =>
                {
                    b.HasOne("EDI.DataAccess.Entities.PlaceLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiInvoice", b =>
                {
                    b.HasOne("EDI.DataAccess.Entities.NameAndAddress", "Invoicee")
                        .WithMany()
                        .HasForeignKey("InvoiceeId");

                    b.Navigation("Invoicee");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiScheduleAgreement", b =>
                {
                    b.HasOne("EDI.DataAccess.Entities.NameAndAddress", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.LineItem", b =>
                {
                    b.HasOne("EDI.DataAccess.Entities.Quantity", "BackorderedQuantity")
                        .WithMany()
                        .HasForeignKey("BackorderedQuantityId");

                    b.HasOne("EDI.DataAccess.Entities.EdiInvoice", null)
                        .WithMany("LineItems")
                        .HasForeignKey("EdiInvoiceId");

                    b.HasOne("EDI.DataAccess.Entities.EdiOrderChange", null)
                        .WithMany("LineItems")
                        .HasForeignKey("EdiOrderChangeId");

                    b.HasOne("EDI.DataAccess.Entities.EdiOrderConfirmation", null)
                        .WithMany("LineItems")
                        .HasForeignKey("EdiOrderConfirmationId");

                    b.HasOne("EDI.DataAccess.Entities.EdiOrder", null)
                        .WithMany("LineItems")
                        .HasForeignKey("EdiOrderId");

                    b.HasOne("EDI.DataAccess.Entities.EdiScheduleAgreement", null)
                        .WithMany("LineItems")
                        .HasForeignKey("EdiScheduleAgreementId");

                    b.HasOne("EDI.DataAccess.Entities.Quantity", "Quantity")
                        .WithMany()
                        .HasForeignKey("QuantityId");

                    b.HasOne("EDI.DataAccess.Entities.Quantity", "ReceivedQuantity")
                        .WithMany()
                        .HasForeignKey("ReceivedQuantityId");

                    b.HasOne("EDI.DataAccess.Entities.ScheduleCondition", "ScheduleCondition")
                        .WithMany()
                        .HasForeignKey("ScheduleConditionId");

                    b.HasOne("EDI.DataAccess.Entities.Quantity", "ScheduledQuantity")
                        .WithMany()
                        .HasForeignKey("ScheduledQuantityId");

                    b.Navigation("BackorderedQuantity");

                    b.Navigation("Quantity");

                    b.Navigation("ReceivedQuantity");

                    b.Navigation("ScheduleCondition");

                    b.Navigation("ScheduledQuantity");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.NameAndAddress", b =>
                {
                    b.HasOne("EDI.DataAccess.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("EDI.DataAccess.Entities.FinancialInstitution", "FinancialInstitution")
                        .WithMany()
                        .HasForeignKey("FinancialInstitutionId");

                    b.HasOne("EDI.DataAccess.Entities.PlaceLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Contact");

                    b.Navigation("FinancialInstitution");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.ScheduleCondition", b =>
                {
                    b.HasOne("EDI.DataAccess.Entities.Quantity", "Quantity")
                        .WithMany()
                        .HasForeignKey("QuantityId");

                    b.Navigation("Quantity");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiInvoice", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiOrder", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiOrderChange", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiOrderConfirmation", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("EDI.DataAccess.Entities.EdiScheduleAgreement", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
