using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EDI.DataAccess.Migrations
{
    public partial class AddDeliveryNote : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "EDI_DeliveryNote",
                schema: "dbo",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    DeliveryDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ArrivalDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DespatchDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    TransportReferenceQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TransportReferenceNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConveyanceReferenceQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConveyanceReferenceNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Carrier_PartyQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Carrier_PartyId = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Carrier_ResponsibleAgency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Carrier_CompanyName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Carrier_Street = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Carrier_CityName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Carrier_Postcode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Carrier_CountryCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreightForwarder_PartyQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreightForwarder_PartyId = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreightForwarder_ResponsibleAgency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreightForwarder_CompanyName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreightForwarder_Street = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreightForwarder_CityName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreightForwarder_Postcode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreightForwarder_CountryCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_PlaceLocationQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_PlaceLocationIdentification = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeliveryCondition1_FunctionCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeliveryCondition1_Code = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeliveryCondition1_PlaceLocationQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeliveryCondition1_PlaceLocationIdentification = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TransportStageQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ModeOfTransportCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TypeOfMeansTransportCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HierarchicalIdNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PackagingLevelCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumberOfPackages = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PackagingRelatedInformationCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PackagingTermsConditionsCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TypeOfPackagesIdentification = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PACCodeListResponsibleAgencyCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GrossMeasurementApplicationQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GrossMeasurementDimensionCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GrossMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GrossMeasurementValue = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NetMeasurementApplicationQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NetMeasurementDimensionCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NetMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NetMeasurementValue = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VolumeMeasurementApplicationQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VolumeMeasurementDimensionCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VolumeMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VolumeMeasurementValue = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MaximumQuantityQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MaximumQuantity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MaximumQTYMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PackageQuantityQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PackageQuantity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PackageQTYMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MarkingInstructionsCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TypeOfMarkingCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PCICodeListResponsibleAgencyCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLIdentityNumberQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLFirstIdentityNumber1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLLastIdentityNumber1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLFirstIdentityNumber2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLLastIdentityNumber2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLFirstIdentityNumber3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLLastIdentityNumber3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLFirstIdentityNumber4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLLastIdentityNumber4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLFirstIdentityNumber5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MLLastIdentityNumber5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWIdentityNumberQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWFirstIdentityNumber1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWLastIdentityNumber1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWFirstIdentityNumber2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWLastIdentityNumber2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWFirstIdentityNumber3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWLastIdentityNumber3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWFirstIdentityNumber4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWLastIdentityNumber4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWFirstIdentityNumber5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AWLastIdentityNumber5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerHierarchicalIdNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerPackagingLevelCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerNumberOfPackages = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerPackagingRelatedInformationCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerPackagingTermsConditionsCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerTypeOfPackagesIdentification = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerPACCodeListResponsibleAgencyCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerGrossMeasurementApplicationQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerGrossMeasurementDimensionCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerGrossMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerGrossMeasurementValue = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerNetMeasurementApplicationQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerNetMeasurementDimensionCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerNetMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerNetMeasurementValue = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerVolumeMeasurementApplicationQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerVolumeMeasurementDimensionCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerVolumeMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerVolumeMeasurementValue = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMaximumQuantityQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMaximumQuantity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InnerMaximumQTYMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerPackageQuantityQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerPackageQuantity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InnerPackageQTYMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMarkingInstructionsCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerTypeOfMarkingCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerPCICodeListResponsibleAgencyCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLIdentityNumberQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLFirstIdentityNumber1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLLastIdentityNumber1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLFirstIdentityNumber2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLLastIdentityNumber2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLFirstIdentityNumber3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLLastIdentityNumber3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLFirstIdentityNumber4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLLastIdentityNumber4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLFirstIdentityNumber5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMLLastIdentityNumber5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedUserId = table.Column<string>(type: "nvarchar(36)", maxLength: 36, nullable: true),
                    CreatedUserName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ModifiedUserId = table.Column<string>(type: "nvarchar(36)", maxLength: 36, nullable: true),
                    ModifiedUserName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SSMA_TimeStamp = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: true),
                    HasEdiConvertError = table.Column<bool>(type: "bit", nullable: false),
                    EdiConvertErrorMessage = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SyntaxIdentifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SyntaxVersionNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SenderUniqueId = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SenderCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RecipientUniqueId = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RecipientCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DateOfPreparation = table.Column<DateTime>(type: "datetime2", nullable: true),
                    InterchangeControlReference = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsTestMessage = table.Column<bool>(type: "bit", nullable: true),
                    Status = table.Column<int>(type: "int", nullable: true),
                    SendErrorMessage = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SendErrorCount = table.Column<int>(type: "int", nullable: false),
                    SendValidationError = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DocumentNameCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DocumentNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MessageFunction = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DocumentDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UnhMessageReferenceNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TypeIdentifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TypeVersionNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TypeReleaseNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ControllingAgency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TextSubjectqualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreeTextCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TextLiteralFreeText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MessageReferenceNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Supplier_PartyQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Supplier_PartyId = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Supplier_ResponsibleAgency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Supplier_CompanyName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Supplier_Street = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Supplier_CityName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Supplier_Postcode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Supplier_CountryCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_PartyQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_PartyId = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_ResponsibleAgency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_CompanyName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_PartyName1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_PartyName2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_Street = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_CityName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_Postcode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Delivery_CountryCode = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EDI_DeliveryNote", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "EDI_LineItemDeliveryNote",
                schema: "dbo",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CountryOriginCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GoodsIdentityNumberQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GoodsIdentityNumberRange = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RelatedSetIdentificationQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RelatedIdentityNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RelatedIdentityNumberQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ManufacturingDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    MonetaryAmountTypeQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MonetaryAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CurrencyCoded = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PurchaseReferenceQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PurchaseReferenceNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PurchaseLineNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PurchaseDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DespatchReferenceQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DespatchReferenceNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DespatchLineNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DespatchDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    EdiDeliveryNoteId = table.Column<int>(type: "int", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedUserId = table.Column<string>(type: "nvarchar(36)", maxLength: 36, nullable: true),
                    CreatedUserName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ModifiedUserId = table.Column<string>(type: "nvarchar(36)", maxLength: 36, nullable: true),
                    ModifiedUserName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SSMA_TimeStamp = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: true),
                    HasEdiConvertError = table.Column<bool>(type: "bit", nullable: false),
                    EdiConvertErrorMessage = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LineItemNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ItemNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ItemNumberType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplierArticleNumberQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplierArticleNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplierArticleNumberType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ItemDescriptionType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ItemCharacteristicCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ItemDescriptionIdentification = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodeListQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodeListResponsibleAgency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ItemDescription = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    QuantityQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ItemQuantity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    QTYMeasureUnitQualifier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeliveryDate = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EDI_LineItemDeliveryNote", x => x.Id);
                    table.ForeignKey(
                        name: "FK_EDI_LineItemDeliveryNote_EDI_DeliveryNote_EdiDeliveryNoteId",
                        column: x => x.EdiDeliveryNoteId,
                        principalSchema: "dbo",
                        principalTable: "EDI_DeliveryNote",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_EDI_LineItemDeliveryNote_EdiDeliveryNoteId",
                schema: "dbo",
                table: "EDI_LineItemDeliveryNote",
                column: "EdiDeliveryNoteId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "EDI_LineItemDeliveryNote",
                schema: "dbo");

            migrationBuilder.DropTable(
                name: "EDI_DeliveryNote",
                schema: "dbo");
        }
    }
}
