eatlab:
  dms:
    api:
      url: http://192.168.0.199:8080

logging:
  level:
    org:
      springframework:
        #data: DEBUG
        #web: DEBUG

---
spring.profiles: dev

eatlab:
  dms:
    api:
      url: http://localhost:8080
    client:
      #cssStyle: OSX